verbose: False

model:
  name: dca
  log_norm: True
  alpha: 10.
  beta: 1.
  gamma: 6.
  lamda: 1.
  encoder:
    units: [64, 64]
    batchnorm: True
    dropout: 0.1
  decoder:
    units: [64, 64]
    batchnorm: True
    dropout: 0.1

dataset:
  name: cortex
  train_percent: 0.8
  labels_percent: 0.1
  batch_size: 64
  dropout_rate: 0.2
  retain_rate: 0.2

variables:
  latents:
    event_shape: 12
    posterior: 'diag'
    kwargs: {}
  transcriptomic:
    posterior: 'zinbd'
    kwargs: {}
  chromatin:
    posterior: 'zinbd'
    kwargs: {}
  proteomic:
    posterior: 'nb'
    kwargs: {}
  celltype:
    posterior: 'onehot'
    kwargs: {}

train:
  optimizer: adam
  learning_rate: 1e-3
  valid_freq: 500
  valid_interval: 0
  clipnorm: 100
  epochs: 500
  max_iter: -1
  sample_shape: []
  logging_interval: 2
  earlystop_threshold: 0.001
  earlystop_progress_length: 0
  earlystop_patience: 20
  earlystop_min_epoch: -1
  terminate_on_nan: True
  allow_rollback: False
  allow_none_gradients: False
  track_gradient_norms: False
