train:
  optimizer: 'sgd'
  learning_rate: 1e-4
  clipnorm: 100
  n_mcmc: 1
  semi_percent: 0.8
  semi_weight: 10.
  corruption_rate: 0.25
  corruption_dist: 'binomial'
  batch_size: 64
  epochs: 2
  callbacks:
  validation_split: 0.1
  validation_freq: 1
  min_delta: 0.5
  min_epoch: 80
  patience: 25
  allow_rollback: True
  terminate_on_nan: True
  checkpoint:
  shuffle: True
  verbose: 1
